=== BlueBananasaurus/Znackovaci-jazyky/game_save.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="quality_set">
    <xs:restriction base="xs:string">
      <xs:pattern value="low|medium|high|ultra"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="aliasing_set">
    <xs:restriction base="xs:string">
      <xs:pattern value="FXAA|none"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="directx_set">
    <xs:restriction base="xs:string">
      <xs:pattern value="Dx10|Dx11|Dx12"/>
    </xs:restriction>
  </xs:simpleType>
    <xs:simpleType name="savename_set">
      <xs:restriction base="xs:string">
        <xs:pattern value="screen-id([0-9])*\.png"/>
      </xs:restriction>
    </xs:simpleType>
  <xs:element name="game_root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="game_setup">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="active_resolution">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="horizontal" type="xs:unsignedShort" />
                    <xs:element name="vertical" type="xs:unsignedShort" />
                    <xs:element name="frequency" type="xs:unsignedByte" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="graphic_setup">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="textures_quality" type="quality_set" />
                    <xs:element name="shadows_quality" type="quality_set" />
                    <xs:element name="water_quality" type="quality_set" />
                    <xs:element name="LOD_fade_out" type="quality_set" />
                    <xs:element name="effect_quality" type="quality_set" />
                    <xs:element name="world_reflections" type="xs:boolean" />
                    <xs:element name="water_reflections" type="xs:boolean" />
                    <xs:element name="post_process" type="xs:boolean" />
                    <xs:element name="complex_scenery" type="xs:boolean" />
                    <xs:element name="antialiasing" type="aliasing_set" />
                  </xs:sequence>
                  <xs:attribute name="directX" type="directx_set" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="key_mapping">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="keyboard">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="key">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="mapped_key" type="xs:string" />
                                <xs:element name="mapped_to" type="xs:string" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="version" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="save_game_master">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="save_game">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="saved_game_stats">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="seconds_played" type="xs:unsignedInt" />
                          <xs:element name="load_count" type="xs:unsignedShort" />
                          <xs:element name="date" type="xs:date" />
                          <xs:element name="time" type="xs:time" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="player">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="position">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="x" type="xs:int" />
                                <xs:element name="y" type="xs:int" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="velocity">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="x" type="xs:int" />
                                <xs:element name="y" type="xs:int" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="in_air" type="xs:boolean" />
                          <xs:element name="in_water" type="xs:boolean" />
                          <xs:element name="on_ladder" type="xs:boolean" />
                          <xs:element name="stats">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="level">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:unsignedByte">
                                        <xs:attribute name="xp" type="xs:unsignedShort" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="health">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:unsignedShort">
                                        <xs:attribute name="poisoned_level" type="xs:unsignedShort" use="required" />
                                        <xs:attribute name="poison_left" type="xs:unsignedShort" use="required" />
                                        <xs:attribute name="on_fire_level" type="xs:unsignedShort" use="required" />
                                        <xs:attribute name="fire_left" type="xs:unsignedShort" use="required" />
                                        <xs:attribute name="air_left" type="xs:unsignedShort" use="required" />
                                        <xs:attribute name="rads" type="xs:unsignedShort" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="strenght">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:unsignedByte">
                                        <xs:attribute name="penalty" type="xs:unsignedByte" use="required" />
                                        <xs:attribute name="penalty_left" type="xs:unsignedByte" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="inteligence">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:unsignedByte">
                                        <xs:attribute name="penalty" type="xs:unsignedByte" use="required" />
                                        <xs:attribute name="penalty_left" type="xs:unsignedByte" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="stamina">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:unsignedByte">
                                        <xs:attribute name="penalty" type="xs:unsignedByte" use="required" />
                                        <xs:attribute name="penalty_left" type="xs:unsignedByte" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="endurance">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:unsignedByte">
                                        <xs:attribute name="penalty" type="xs:unsignedByte" use="required" />
                                        <xs:attribute name="penalty_left" type="xs:unsignedByte" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="luck">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:unsignedByte">
                                        <xs:attribute name="penalty" type="xs:unsignedByte" use="required" />
                                        <xs:attribute name="penalty_left" type="xs:unsignedByte" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="inventory">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element maxOccurs="unbounded" name="item_id">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="amount" type="xs:unsignedShort" />
                                      <xs:element minOccurs="0" maxOccurs="1" name="modifier_0" type="xs:int" />
                                      <xs:element minOccurs="0" maxOccurs="1" name="modifier_1" type="xs:int" />
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:unsignedShort" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="enemies">
                      <xs:complexType mixed="true">
                        <xs:sequence minOccurs="0">
                          <xs:element maxOccurs="unbounded" name="enemy">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="position">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="x" type="xs:int" />
                                      <xs:element name="y" type="xs:int" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="velocity">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="x" type="xs:int" />
                                      <xs:element name="y" type="xs:int" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="in_air" type="xs:boolean" />
                                <xs:element name="in_water" type="xs:boolean" />
                                <xs:element name="stats">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="level" type="xs:unsignedByte" />
                                      <xs:element name="health">
                                        <xs:complexType>
                                          <xs:simpleContent>
                                            <xs:extension base="xs:unsignedShort">
                                              <xs:attribute name="poisoned_level" type="xs:unsignedByte" use="required" />
                                              <xs:attribute name="poison_left" type="xs:unsignedByte" use="required" />
                                              <xs:attribute name="on_fire_level" type="xs:unsignedByte" use="required" />
                                              <xs:attribute name="fire_left" type="xs:unsignedByte" use="required" />
                                              <xs:attribute name="air_left" type="xs:unsignedByte" use="required" />
                                              <xs:attribute name="rads" type="xs:unsignedShort" use="required" />
                                            </xs:extension>
                                          </xs:simpleContent>
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element name="strenght">
                                        <xs:complexType>
                                          <xs:simpleContent>
                                            <xs:extension base="xs:unsignedByte">
                                              <xs:attribute name="penalty" type="xs:short" use="required" />
                                              <xs:attribute name="penalty_left" type="xs:unsignedShort" use="required" />
                                            </xs:extension>
                                          </xs:simpleContent>
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element name="drops">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element maxOccurs="unbounded" name="item_id">
                                              <xs:complexType mixed="true">
                                                <xs:sequence minOccurs="0">
                                                  <xs:element name="amount" type="xs:unsignedShort" />
                                                  <xs:element minOccurs="0" name="modifier_0" type="xs:int"/>
                                                  <xs:element minOccurs="0" name="modifier_1" type="xs:int" />
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:unsignedShort" use="required" />
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="monster" type="xs:string" use="required" />
                              <xs:attribute name="monster_id" type="xs:unsignedShort" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:unsignedByte" use="required" />
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="save_screenshot" type="savename_set" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="orderid" type="xs:unsignedInt" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== BlueBananasaurus/Znackovaci-jazyky/game_save.xml
<?xml version="1.0" encoding="UTF-8"?>
<game_root orderid="889923"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="game_save.xsd">
  <game_setup version="8.9.1">
    <active_resolution>
      <horizontal>800</horizontal>
      <vertical>600</vertical>
      <frequency>70</frequency>
    </active_resolution>
    <graphic_setup directX ="Dx10">
      <textures_quality>medium</textures_quality>
      <shadows_quality>medium</shadows_quality>
      <water_quality>medium</water_quality>
      <LOD_fade_out>medium</LOD_fade_out>
      <effect_quality>ultra</effect_quality>
      <world_reflections>false</world_reflections>
      <water_reflections>true</water_reflections>
      <post_process>true</post_process>
      <complex_scenery>true</complex_scenery>
      <antialiasing>FXAA</antialiasing>
    </graphic_setup>
    <key_mapping>
      <keyboard>
        <key>
          <mapped_key>A</mapped_key>
          <mapped_to>left</mapped_to>
        </key>
        <key>
          <mapped_key>D</mapped_key>
          <mapped_to>right</mapped_to>
        </key>
        <key>
          <mapped_key>S</mapped_key>
          <mapped_to>crouch</mapped_to>
        </key>
        <key>
          <mapped_key>Space</mapped_key>
          <mapped_to>jump</mapped_to>
        </key>
      </keyboard>
    </key_mapping>
  </game_setup>
  <save_game_master>
    <save_game id="1" name="Muj sejf 111" save_screenshot="screen-id1.png">
      <saved_game_stats>
        <seconds_played>8876</seconds_played>
        <load_count>56</load_count>
        <date>2017-03-15</date>
        <time>10:30:17</time>
      </saved_game_stats>
      <player name="LOL">
        <position>
          <x>765</x>
          <y>986</y>
        </position>
        <velocity>
          <x>0</x>
          <y>9</y>
        </velocity>
        <in_air>false</in_air>
        <in_water>true</in_water>
        <on_ladder>false</on_ladder>
        <stats>
          <level xp="5675">6</level>
          <health poisoned_level="0" poison_left="0" on_fire_level="1" fire_left="6" air_left="100" rads="455">89</health>
          <strenght penalty="0" penalty_left="0">8</strenght>
          <inteligence penalty="3" penalty_left="16">9</inteligence>
          <stamina penalty="0" penalty_left="0">8</stamina>
          <endurance penalty="0" penalty_left="0">5</endurance>
          <luck penalty="0" penalty_left="0">1</luck>
        </stats>
        <inventory>
          <item_id id="1">
            <amount>5</amount>
            <modifier_0>80</modifier_0>
            <modifier_1>50</modifier_1>
          </item_id>
          <item_id id="2">
            <amount>25</amount>
            <modifier_1>15112</modifier_1>
          </item_id>
          <item_id id="3">
            <amount>256</amount>
            <modifier_0>1</modifier_0>
          </item_id>
          <item_id id="1000">
            <amount>50</amount>
            <modifier_0>0</modifier_0>
            <modifier_1>0</modifier_1>
          </item_id>
        </inventory>
      </player>
      <enemies>
        <enemy monster = "ghoul" monster_id="1">
          <position>
            <x>765</x>
            <y>986</y>
          </position>
          <velocity>
            <x>0</x>
            <y>9</y>
          </velocity>
          <in_air>false</in_air>
          <in_water>true</in_water>
          <stats>
            <level>2</level>
            <health poisoned_level="0" poison_left="0" on_fire_level="0" fire_left="0" air_left="100" rads="455">200</health>
            <strenght penalty="0" penalty_left="0">12</strenght>
            <drops>
              <item_id id="1">
                <amount>5</amount>
                <modifier_0>80</modifier_0>
                <modifier_1>50</modifier_1>
              </item_id>
              <item_id id="5">
                <amount>5</amount>
                <modifier_0>10</modifier_0>
              </item_id>
              <item_id id="256">
                <amount>5</amount>
              </item_id>
            </drops>
          </stats>
        </enemy>
        <enemy monster = "very_evil_monkey" monster_id="2">
          <position>
            <x>836</x>
            <y>873</y>
          </position>
          <velocity>
            <x>89</x>
            <y>0</y>
          </velocity>
          <in_air>true</in_air>
          <in_water>false</in_water>
          <stats>
            <level>24</level>
            <health poisoned_level="0" poison_left="0" on_fire_level="0" fire_left="0" air_left="100" rads="0">1024</health>
            <strenght penalty="0" penalty_left="0">78</strenght>
            <drops>
              <item_id id="666">
                <amount>666</amount>
                <modifier_0>0</modifier_0>
                <modifier_1>5</modifier_1>
              </item_id>
            </drops>
          </stats>
        </enemy>
      </enemies>
    </save_game>
    <save_game id="2" name="ASDFG" save_screenshot="screen-id2.png">
      <saved_game_stats>
        <seconds_played>4155</seconds_played>
        <load_count>10</load_count>
        <date>2017-01-15</date>
        <time>01:10:01</time>
      </saved_game_stats>
      <player name="LOL">
        <position>
          <x>1024</x>
          <y>65000</y>
        </position>
        <velocity>
          <x>0</x>
          <y>0</y>
        </velocity>
        <in_air>false</in_air>
        <in_water>true</in_water>
        <on_ladder>false</on_ladder>
        <stats>
          <level xp="1245">6</level>
          <health poisoned_level="0" poison_left="0" on_fire_level="1" fire_left="6" air_left="100" rads="455">125</health>
          <strenght penalty="0" penalty_left="0">1</strenght>
          <inteligence penalty="3" penalty_left="16">6</inteligence>
          <stamina penalty="0" penalty_left="0">8</stamina>
          <endurance penalty="0" penalty_left="0">2</endurance>
          <luck penalty="0" penalty_left="0">1</luck>
        </stats>
        <inventory>
          <item_id id="16">
            <amount>5</amount>
            <modifier_0>10</modifier_0>
            <modifier_1>500</modifier_1>
          </item_id>
          <item_id id="2">
            <amount>25</amount>
            <modifier_1>151</modifier_1>
          </item_id>
        </inventory>
      </player>
      <enemies>
        <enemy monster = "ghoul" monster_id="1">
          <position>
            <x>765</x>
            <y>986</y>
          </position>
          <velocity>
            <x>0</x>
            <y>9</y>
          </velocity>
          <in_air>false</in_air>
          <in_water>true</in_water>
          <stats>
            <level>2</level>
            <health poisoned_level="0" poison_left="0" on_fire_level="0" fire_left="0" air_left="100" rads="455">200</health>
            <strenght penalty="0" penalty_left="0">12</strenght>
            <drops>
              <item_id id="1">
                <amount>5</amount>
                <modifier_0>80</modifier_0>
                <modifier_1>50</modifier_1>
              </item_id>
              <item_id id="5">
                <amount>5</amount>
                <modifier_0>10</modifier_0>
              </item_id>
              <item_id id="256">
                <amount>5</amount>
              </item_id>
            </drops>
          </stats>
        </enemy>
        <enemy monster = "poor_bear" monster_id="54">
          <position>
            <x>-836</x>
            <y>10025</y>
          </position>
          <velocity>
            <x>24</x>
            <y>0</y>
          </velocity>
          <in_air>true</in_air>
          <in_water>false</in_water>
          <stats>
            <level>24</level>
            <health poisoned_level="0" poison_left="0" on_fire_level="0" fire_left="0" air_left="100" rads="0">1024</health>
            <strenght penalty="0" penalty_left="0">78</strenght>
            <drops>
              <item_id id="12">
                <amount>5</amount>
                <modifier_0>145</modifier_0>
                <modifier_1>789</modifier_1>
              </item_id>
            </drops>
          </stats>
        </enemy>
      </enemies>
    </save_game>
    <save_game id="3" name="save dalsi" save_screenshot="screen-id3.png">
      <saved_game_stats>
        <seconds_played>84555</seconds_played>
        <load_count>10</load_count>
        <date>2014-10-31</date>
        <time>12:34:32</time>
      </saved_game_stats>
      <player name="LOL">
        <position>
          <x>1024</x>
          <y>65000</y>
        </position>
        <velocity>
          <x>0</x>
          <y>0</y>
        </velocity>
        <in_air>false</in_air>
        <in_water>true</in_water>
        <on_ladder>false</on_ladder>
        <stats>
          <level xp="45888">32</level>
          <health poisoned_level="0" poison_left="0" on_fire_level="1" fire_left="6" air_left="100" rads="455">125</health>
          <strenght penalty="0" penalty_left="0">1</strenght>
          <inteligence penalty="0" penalty_left="0">6</inteligence>
          <stamina penalty="0" penalty_left="0">4</stamina>
          <endurance penalty="0" penalty_left="0">3</endurance>
          <luck penalty="0" penalty_left="0">1</luck>
        </stats>
        <inventory>
          <item_id id="16">
            <amount>5</amount>
            <modifier_0>10</modifier_0>
            <modifier_1>500</modifier_1>
          </item_id>
          <item_id id="2">
            <amount>25</amount>
            <modifier_1>151</modifier_1>
          </item_id>
        </inventory>
      </player>
      <enemies></enemies>
    </save_game>
    <save_game id="4" name="save dalsi" save_screenshot="screen-id4.png">
      <saved_game_stats>
        <seconds_played>14455</seconds_played>
        <load_count>10</load_count>
        <date>2015-02-12</date>
        <time>12:34:32</time>
      </saved_game_stats>
      <player name="LOL">
        <position>
          <x>1024</x>
          <y>65000</y>
